#!/bin/bash
#
#  Copyright (c) 2020, Lukasz Duda.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Fulfilling dependencies of the project.
#

set -exo pipefail

install_packages()
{
    echo 'Downloading package information from configured sources...'
    sudo apt-get update

    echo 'Installing required dependency...'
    sudo apt-get install --no-install-recommends --allow-unauthenticated -y \
        docker wget qemu qemu-user-static
}

initialize_submodules()
{
    echo 'Initializing git submodules...'
    git submodule update --init
}

download_rpi_image()
{
    mkdir -p images
    IMAGE_FILE=images/raspbian.img

    if [ ! -f "$IMAGE_FILE" ]; then
        echo 'Downloading Raspbian image...'

        if [ -z $IMAGE_URL]
        then
            IMAGE_URL=http://director.downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-06-24/2019-06-20-raspbian-buster-lite.zip
        fi

        wget -O images/raspbian.zip $IMAGE_URL
        unzip -o images/raspbian.zip -d images
        mv images/*.img images/raspbian.img
        rm images/raspbian.zip
    fi
}

main()
{
    install_packages
    initialize_submodules
    download_rpi_image
}

main
